CREATE TABLE games (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  genre VARCHAR(255) NOT NULL,
  multiplayer BOOLEAN NOT NULL,
  last_played_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE authors (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);
