CREATE TABLE games (
  id INT NOT NULL AUTO_INCREMENT,
  genre_id INT NOT NULL,
  author_id INT NOT NULL,
  source_id INT NOT NULL,
  label_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  multiplayer BOOLEAN NOT NULL,
  last_played_at DATE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (genre_id) REFERENCES genres (id),
  FOREIGN KEY (author_id) REFERENCES authors (id),
  FOREIGN KEY (source_id) REFERENCES sources (id),
  FOREIGN KEY (label_id) REFERENCES labels (id)
);

-- Authors table
CREATE TABLE authors (
  id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);